package org.atlasalign.application;

public enum ConfidenceMetric {
    SOURCE_IDENTITY,
    ATLAS_ASSET_IDENTITY,
    INITIAL_PLANE_PROVENANCE,
    DEEPSLICE_INPUT_IDENTITY,
    TISSUE_MASK_COMPLETENESS,
    ATLAS_TISSUE_DICE,
    BOUNDARY_DISTANCE,
    STRUCTURAL_SIMILARITY,
    VALID_ATLAS_COVERAGE,
    TRANSFORM_PLAUSIBILITY,
    BEST_SECOND_LEVEL_MARGIN,
    DEEPSLICE_MODEL_DISAGREEMENT,
    DEEPSLICE_AP_DISAGREEMENT,
    DEEPSLICE_SAGITTAL_TILT_DISAGREEMENT,
    DEEPSLICE_HORIZONTAL_TILT_DISAGREEMENT,
    DEEPSLICE_PHYSICAL_PLANE_DISAGREEMENT,
    PARTIAL_CONDITION_SPREAD,
    LATERALITY_ORIENTATION,
    TISSUE_DAMAGE,
    ACTIVE_LANDMARK_RESIDUAL,
    INDEPENDENT_LANDMARK_RESIDUAL,
    LOCAL_WARP_PLAUSIBILITY,
    SYNTHETIC_PIXEL_EXCLUSION
}
