package org.atlasalign.application;

public enum ReviewAcceptanceBlockReason {
    SOURCE_CHANGED,
    ATLAS_IDENTITY_CHANGED,
    CURRENT_ATLAS_PLANE_NOT_VERIFIED,
    VERIFICATION_FAILED,
    ORIENTATION_UNCONFIRMED,
    LATERALITY_UNSURE,
    LANDMARK_OUT_OF_BOUNDS,
    SYNTHETIC_PROVENANCE_UNVERIFIED,
    WARNINGS_NOT_ACKNOWLEDGED
}
